branch-defaults:
  master:
    environment: CatOrCheese-env
    group_suffix: null
global:
  application_name: app
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 2.7
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
